version: "3.7"
services:
  web:
    container_name: cleanArchitectureService
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/server
    environment:
      MYSQL_DATABASE: clean_architecture
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: 0.0.0.0
      APPLICATION_SERVER_PORT: 3000
      APP_FORCE_SHUTDOWN_SECOND: 30
      API_KEY: abcd
